### ISSUE TITLE
"gem install rultor" breaks ruby installation

### ISSUE THREAD

**Issue by rfqu** [yegor256/rultor-remote#10]
File README.md reads:
Install it first:

```bash
$ gem install rultor
```

This works, and then rultor could be run (and issue #7 could be reproduced).
However, after changing the project, next attempt to install fails:

```
# sudo gem install rultor
/usr/local/lib/site_ruby/1.9.1/rubygems/version.rb:206:in `initialize': Malformed version number string ruby (ArgumentError)
	from /usr/local/lib/site_ruby/1.9.1/rubygems/version.rb:198:in `new'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/version.rb:198:in `new'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/stub_specification.rb:41:in `initialize'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/stub_specification.rb:123:in `new'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/stub_specification.rb:123:in `block in data'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/stub_specification.rb:112:in `open'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/stub_specification.rb:112:in `data'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/stub_specification.rb:203:in `valid?'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:748:in `select'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:748:in `gemspec_stubs_in'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:773:in `block in map_stubs'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:770:in `each'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:770:in `flat_map'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:770:in `map_stubs'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:762:in `installed_stubs'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:830:in `stubs'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:724:in `_all'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/specification.rb:1122:in `latest_specs'
	from /usr/local/lib/site_ruby/1.9.1/rubygems.rb:466:in `find_latest_files'
	from /usr/local/lib/site_ruby/1.9.1/rubygems.rb:994:in `load_plugins'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/gem_runner.rb:81:in `<top (required)>'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/bin/gem:9:in `<main>'
```

As we see, the error is in a system file  /usr/local/lib/site_ruby/1.9.1/rubygems/version.rb. No one file from the "rultor-remote" project is used.

**Comment by alex-palevsky** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@rfqu looks like this problem is related to your local system... how can I reproduce it?

**Comment by rfqu** [comment]
@yegor256 the problem occur on a Linux Mint installed in VirtualBox. Now I moved to a Ubuntu Mate installed directly on hardware and problem does not reproduce. So this issue can be closed. But I have another problem and do not know what to do - file it as a bug (against what?) or continue to learn ruby system: "gem build rultor.gemspec" produces new file rultor-1.0.snapshot.gem, but "gem instal rultor" installs rultor-0.4.1 with unmodified content. Is there a document how to build and test rultor-remote project?

**Comment by rfqu** [comment]
Closed as not reproducible.

**Comment by yegor256** [comment]
@rfqu well, yes, you have to know ruby a little bit in order to test this project. But if just want to use it as a user, you can just `gem install rultor` and then run `rultor`. It should work. If it doesn't, it's a bug, you can file it here. But keep in mind that when you file it you should explain how I (or anyone else) can reproduce it, step by step.
