### ISSUE TITLE
file README.md is misleading; file lib/rultor/version.rb has wrong value

### ISSUE THREAD

**Issue by rfqu** [yegor256/rultor-remote#11]
File README.md reads: 
Install it first:
```bash
$ gem install rultor
```
This command installs rultor gem from network (site rubygems.org), since current directory does not contain gem built from sources. So it should be changed to:
Build it first:
```bash
$ gem build rultor.gemspec
```
Then install it:
```bash
$ gem install rultor

However, these commands still install rultor gem from network, because file lib/rultor/version.rb contains text:
  VERSION = '1.0.snapshot'
and "gem install" command ignores built gems with letters in version number.
So it should be changed to something like 
  VERSION = '0.4.2'
because the last version of rultor gem on rubygems.org is 0.4.1.

**Comment by yegor256** [comment]
@rfqu I'm not sure I understand... I run this on a clean Ubuntu and it work:

```
gem install rultor
```

No need to build it first. The gem is installed right from the rubygems repository. Or I miss something?

**Comment by rfqu** [comment]
The gem from repository is not quite good (bug #7 is filed against it). The README file should explain how to build gem from sources. Otherwise, what for all that sources exist? Just remove them.

**Comment by yegor256** [comment]
@rfqu take a look at 2057381 better? I can try to add more if it's not clear

**Comment by rfqu** [comment]
@yegor256 Also, following questions should be covered:
- how to run tests
- how to choose version number
- when and how put gem into global repositoty (rubygems.org).

**Comment by yegor256** [comment]
@rfqu `rake` runs all tests, it's a build automation tool, similar to Maven in Java world. you don't need to chose version number or deploy to rubygems, in order to contribute. these tasks are done by the project architect

**Comment by rfqu** [comment]
@yegor256 In order to contribute, I need to deploy to local repository and then run the gem to see it works. In order to deploy to local repository, I need to change version number from '1.0.snapshot' to something without letters - and then save it to github. 
I agree with the rest of explanations, but they should be written in the readme file.

**Comment by yegor256** [comment]
@rfqu I've never done what you just explained. Even though I created this tool. You don't need to do all this. You have integration tests, which help you to test the tool, without installing it locally, like you explained. They are in `features/` directory.

**Comment by rfqu** [comment]
@yegor256 "You don't need to do all this"
Then what do I have to do? I see this project first time in a life. I look at the readme file and see: "Install it first". So, you confirm that readme file is misleading. Then why don't you approve the bug report?

**Comment by rfqu** [comment]
@yegor256 "They are in features/ directory"
I see 2 kinds of files in  in features/ directory:  of type *.feature and of type *.rb. The last, I guess, are ruby executables  - but their execution fail. How *.feature files can be executed?

**Comment by yegor256** [comment]
@rfqu that's basic principles of Ruby projects, I don't think we need to explain them in README. Looks like you were assigned to this project/issue by mistake (since you're a Java dev). If you don't like the ticket, just ask us to re-assign...
