### ISSUE TITLE
rakefile is broken

### ISSUE THREAD

**Issue by rfqu** [yegor256/rultor-remote#12]
rake fails on commit 6224bb1ec9fe57d0151893a0f92e68425c3d4cc9 (made dec 24):

```
$ rake --trace
/home/rfq/teamed.io/rultor-remote/Rakefile:36: warning: already initialized constant CLEAN
/usr/lib/ruby/vendor_ruby/rake/clean.rb:61: warning: previous definition of CLEAN was here
rake aborted!
LoadError: cannot load such file -- rubocop/rake_task
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/rfq/teamed.io/rultor-remote/Rakefile:65:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:77:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `<main>'
```

This bug blocks fixing issue #7.

**Comment by alex-palevsky** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@rfqu did you try this (as README suggests)?:

```
bundle install
rake --trace
```

**Comment by rfqu** [comment]
after bundle install, rake --trace fails:
$ rake --trace
/home/rfq/git/rultor-remote/Rakefile:36: warning: already initialized constant CLEAN
/usr/lib/ruby/vendor_ruby/rake/clean.rb:61: warning: previous definition of CLEAN was here
** Invoke default (first_time)
** Invoke clean (first_time)
** Execute clean
** Invoke test (first_time)
** Execute test
Run options: --seed 26283

# Running:

"log works"
.+ set -e
+ file=secret.txt
+ enc=secret.txt.enc
+ [ -e secret.txt.enc ]
+ asc=secret.txt.asc
+ [ -e secret.txt.asc ]
+ dir=/tmp/test20160102-30322-15dp6ha
+ gpg --version
gpg (GnuPG) 1.4.18
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
+ gpg --symmetric --armor --verbose --batch --no-tty --passphrase rultor-key:test -o secret.txt.enc /tmp/test20160102-30322-15dp6ha/secret.txt
gpg: gpg-agent is not available in this session
gpg: using cipher CAST5
gpg: writing to `secret.txt.enc'
+ gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C
gpg: requesting key 9AF0FA4C from hkp server pool.sks-keyservers.net
gpg: armor header: Version: SKS 1.1.5
gpg: armor header: Comment: Hostname: vm-keyserver.spline.inf.fu-berlin.de
gpg: pub  2048R/9AF0FA4C 2014-08-17  Rultor.com <gpg@rultor.com>
gpg: key 9AF0FA4C: "Rultor.com <gpg@rultor.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ gpg --trust-model always --output secret.txt.asc --batch --no-tty --armor --encrypt --verbose --recipient 9AF0FA4C secret.txt.enc
gpg: using subkey 9A839C3A instead of primary key 9AF0FA4C
gpg: No trust check due to `--trust-model always' option
gpg: reading from `secret.txt.enc'
gpg: writing to `secret.txt.asc'
gpg: RSA/AES256 encrypted for: "9A839C3A Rultor.com <gpg@rultor.com>"
+ rm -f secret.txt.enc
"secret.txt encrypted"
F

Finished in 1.270295s, 1.5744 runs/s, 0.7872 assertions/s.

  1) Failure:
TestEncrypt#test_basic_encryption [/home/rfq/git/rultor-remote/test/test_encrypt.rb:47]:
Expected: true
  Actual: false

2 runs, 1 assertions, 1 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test" -I"/usr/lib/ruby/vendor_ruby" 

Looks like the test "test_encrypt.rb" should be changed according to the new behavior of the Rultor::Encrypt class.

**Comment by rfqu** [comment]
@yegor256 after bundle install, rake --trace fails the same way as at https://travis-ci.org/yegor256/rultor-remote/builds/99379518
I believe a separate issue must be created in order to fix "test_encrypt.rb".

**Comment by yegor256** [comment]
@rfqu I can't reproduce it :( here is my log:

```
$ bundle install
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using json 1.8.2
Using minitest 5.6.1
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.1
Using builder 3.2.2
Using erubis 2.7.0
Using mini_portile 0.6.2
Using nokogiri 1.6.6.2
Using rails-deprecated_sanitizer 1.0.3
Using rails-dom-testing 1.0.6
Using loofah 2.0.1
Using rails-html-sanitizer 1.0.2
Using actionview 4.2.1
Using rack 1.6.0
Using rack-test 0.6.3
Using actionpack 4.2.1
Using activemodel 4.2.1
Using ast 2.0.0
Using parser 2.2.2.2
Using astrolabe 1.3.0
Using unf_ext 0.0.7.1
Using unf 0.1.4
Using domain_name 0.5.24
Using http-cookie 1.0.2
Using mime-types 2.5
Using netrc 0.10.3
Using rest-client 1.8.0
Using docile 1.1.5
Using simplecov-html 0.10.0
Using simplecov 0.10.0
Using tins 1.5.1
Using term-ansicolor 1.3.0
Using thor 0.19.1
Using coveralls 0.8.1
Using diff-lcs 1.2.5
Using multi_json 1.11.0
Using gherkin 2.12.2
Using multi_test 0.1.2
Using cucumber 1.3.11
Using powerpack 0.1.0
Using railties 4.2.1
Using rainbow 2.0.0
Using rdoc 3.12.2
Using rspec-expectations 2.99.2
Using rspec-collection_matchers 1.1.2
Using rspec-core 2.99.2
Using rspec-mocks 2.99.3
Using rspec-rails 2.99.0
Using ruby-progressbar 1.7.5
Using rubocop 0.30.1
Using rubocop-rspec 1.3.0
Using slop 3.6.0
Using rultor 1.0.snapshot from source at .
Using bundler 1.10.6
Bundle complete! 9 Gemfile dependencies, 57 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
/code/rultor-remote$ rake
/Volumes/ssd2/code/rultor-remote/Rakefile:36: warning: already initialized constant CLEAN
/Users/yegor/.rvm/gems/ruby-2.1.3/gems/rake-10.4.2/lib/rake/clean.rb:61: warning: previous definition of CLEAN was here
Run options: --seed 16348

# Running:

+ set -e
+ file=secret.txt
+ enc=secret.txt.enc
+ '[' -e secret.txt.enc ']'
+ asc=secret.txt.asc
+ '[' -e secret.txt.asc ']'
+ cd /var/folders/vl/633jwjvn2jvbj9zfg1sgglhw0000gp/T/test20160104-92726-1r7tqcq
+ gpg --version
gpg (GnuPG) 1.4.19
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
+ gpg --symmetric --armor --verbose --batch --no-tty --passphrase rultor-key:test -o secret.txt.enc secret.txt
gpg: using cipher CAST5
gpg: writing to `secret.txt.enc'
+ gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C
gpg: requesting key 9AF0FA4C from hkp server pool.sks-keyservers.net
gpg: DBG: armor-keys-failed (KEY 0x9AF0FA4C BEGIN
) ->0
gpg: armor header: Version: SKS 1.1.5
gpg: armor header: Comment: Hostname: keys-01.licoho.de
gpg: DBG: armor-keys-failed (KEY 0x9AF0FA4C END
) ->0
gpg: pub  2048R/9AF0FA4C 2014-08-17  Rultor.com <gpg@rultor.com>
gpg: key 9AF0FA4C: "Rultor.com <gpg@rultor.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
+ gpg --trust-model always --output secret.txt.asc --batch --no-tty --armor --encrypt --verbose --recipient 9AF0FA4C secret.txt.enc
gpg: using subkey 9A839C3A instead of primary key 9AF0FA4C
gpg: No trust check due to `--trust-model always' option
gpg: reading from `secret.txt.enc'
gpg: writing to `secret.txt.asc'
gpg: RSA/AES256 encrypted for: "9A839C3A Rultor.com <gpg@rultor.com>"
+ rm -f secret.txt.enc
"secret.txt encrypted"
."log works"
.

Finished in 0.460318s, 4.3448 runs/s, 2.1724 assertions/s.

2 runs, 1 assertions, 0 failures, 0 errors, 0 skips
/Users/yegor/.rvm/rubies/ruby-2.1.3/bin/ruby -S bundle exec cucumber  --profile travis
"logging to stdout"
Using the travis profile...
..............WARNING:  pessimistic dependency on rake (~> 10.4.2, development) may be overly strict
  if rake is semantically versioned, use:
    add_development_dependency 'rake', '~> 10.4', '>= 10.4.2'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
..

5 scenarios (5 passed)
16 steps (16 passed)
0m2.886s
Coverage report generated for Cucumber Features to /Volumes/ssd2/code/rultor-remote/coverage. 10 / 10 LOC (100.0%) covered.
[Coveralls] Outside the CI environment, not sending data.
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.6-compliant syntax, but you are running 2.1.3.
Running RuboCop...
Inspecting 11 files
...........

11 files inspected, no offenses detected
```

**Comment by yegor256** [comment]
@rfqu let me try to configure it for appveyor (Windows)

**Comment by yegor256** [comment]
@rfqu as you see, both Travis and Appveyor builds are clean. I really can't reproduce the bug you're experiencing. Please, try this again:

```
$ bundle update
$ rake
```

**Comment by rfqu** [comment]
@yegor256 description of the issue reads: rake fails on commit 6224bb1
But you checked without that commit. I can see following message in your log:
cd /var/folders/vl/633jwjvn2jvbj9zfg1sgglhw0000gp/T/test20160104-92726-1r7tqcq
In the mentioned commit, cd command is removed.

**Comment by yegor256** [comment]
@rfqu we can only guarantee that master branch (`HEAD`) is clean. If it's broken - it's a bug. All other places in git log are out of scope.

**Comment by rfqu** [comment]
Closed as invalid.
