### ISSUE TITLE
gpg: keyserver receive failed: No route to host

### ISSUE THREAD

**Issue by jachinte** [yegor256/rultor-remote#18]
Hi,
I'm trying to encrypt a file but the rultor CLI fails. It seems like rultor is trying to execute `gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C`, but it fails with the error message `gpg: keyserver receive failed: No route to host`. I did a quick search; the error goes away when you add ipv4: `gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C`, which produces:
```
gpg: data source: http://45.33.82.183:11371
gpg: armor header: Version: SKS 1.1.6
gpg: armor header: Comment: Hostname: keys.fspproductions.biz
gpg: pub  rsa2048/3FD3FA7E9AF0FA4C 2014-08-17  Rultor.com <gpg@rultor.com>
gpg: key 3FD3FA7E9AF0FA4C: "Rultor.com <gpg@rultor.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

Here is the complete output:
<details>
rultor encrypt -p unicesi/amelia ~/.m2/settings.backup.xml                       
+ set -e
+ file=/Users/--/.m2/settings.backup.xml
+ asc=/Users/--/.m2/settings.backup.xml.asc
+ '[' -e /Users/--/.m2/settings.backup.xml.asc ']'
++ mktemp -t rultor-XXXX
+ tmp=/var/folders/k0/7f_5tyms21b_1gcx01wfrp2h0000gn/T/rultor-XXXX.H7GRKDt2
+ rm -f /var/folders/k0/7f_5tyms21b_1gcx01wfrp2h0000gn/T/rultor-XXXX.H7GRKDt2
+ gpg --version
gpg (GnuPG) 2.1.21
libgcrypt 1.7.7
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/--/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
+ gpg --symmetric --armor --verbose --batch --no-tty --passphrase rultor-key:unicesi/amelia -o /var/folders/k0/7f_5tyms21b_1gcx01wfrp2h0000gn/T/rultor-XXXX.H7GRKDt2 /Users/--/.m2/settings.backup.xml
gpg: using cipher AES
gpg: writing to '/var/folders/k0/7f_5tyms21b_1gcx01wfrp2h0000gn/T/rultor-XXXX.H7GRKDt2'
+ gpg --keyserver hkp://pool.sks-keyservers.net --verbose --recv-keys 9AF0FA4C
gpg: keyserver receive failed: No route to host
/usr/local/lib/ruby/gems/2.4.0/gems/rultor-0.4.3/lib/rultor/encrypt.rb:55:in `run': PGP encryption failed (RuntimeError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/rultor-0.4.3/bin/rultor:48:in `block (3 levels) in <top (required)>'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
	from /usr/local/lib/ruby/gems/2.4.0/gems/rultor-0.4.3/bin/rultor:39:in `<top (required)>'
	from /usr/local/bin/rultor:22:in `load'
	from /usr/local/bin/rultor:22:in `<main>'
</details>

I'm running rultor 0.4.3, gpg 2.1.21, mac 10.12.6

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by jachinte** [comment]
I tested it locally and checked that the solution works. I'd create a pull request but I had an issue running rake:

```
rake --trace
/Users/--/Development/repositories/rultor-remote/Rakefile:36: warning: already initialized constant CLEAN
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/clean.rb:62: warning: previous definition of CLEAN was here
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x007fc477883518>
/usr/local/lib/ruby/gems/2.4.0/gems/rubocop-0.35.1/lib/rubocop/rake_task.rb:23:in `initialize'
/Users/--/Development/repositories/rultor-remote/Rakefile:67:in `new'
/Users/--/Development/repositories/rultor-remote/Rakefile:67:in `<top (required)>'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<main>'
```

I'm not a ruby developer so it would take too much time to find out what's happenning.

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.4`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor-remote#18` was not in scope
