### ISSUE TITLE
Rultor installation wants to override rake

### ISSUE THREAD

**Issue by tmoreira2020** [yegor256/rultor-remote#8]
I'm getting the following message during rultor's installation.

```
sudo gem install rultor
rake's executable "rake" conflicts with /usr/bin/rake
Overwrite the executable? [yN]
```

This is the result of uname -a

````
Darwin Thiagos-MacBook-Pro.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
```
rake's version

```
rake, version 0.9.6
```

ruby's version
````
ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```
Not sure if I should accept the overwrite request. Is there a workaround?

**Comment by yegor256** [comment]
@tmoreira2020 yes, indeed, it's a bug at https://github.com/yegor256/rultor-remote/blob/master/rultor.gemspec#L55 Let me try to fix it

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.4.1`

**Comment by yegor256** [comment]
@tmoreira2020 try version 0.4.1, should work

**Comment by tmoreira2020** [comment]
It is fixed! Thanks @yegor256
